import { UsersEntry } from "@/types/accounts.types";

export const mockUsers: UsersEntry[] = [
  {
    id: "usr-001",
    name: "John Smith",
    email: "john.smith@example.com",
    role: "Administrator",
    department: "IT",
    permissionGroup: "Super Admin",
    status: "active",
    lastLogin: "2023-06-15T09:30:00Z",
  },
  {
    id: "usr-002",
    name: "Emily Johnson",
    email: "emily.j@example.com",
    role: "Manager",
    department: "Marketing",
    permissionGroup: "Department Head",
    status: "active",
    lastLogin: "2023-06-14T14:45:00Z",
  },
  {
    id: "usr-003",
    name: "Michael Chen",
    email: "michael.c@example.com",
    role: "Developer",
    department: "Engineering",
    permissionGroup: "Technical Staff",
    status: "active",
    lastLogin: "2023-06-13T11:20:00Z",
  },
  {
    id: "usr-004",
    name: "Sarah Williams",
    email: "sarah.w@example.com",
    role: "Analyst",
    department: "Finance",
    permissionGroup: "Regular User",
    status: "active",
    lastLogin: "2023-06-12T16:10:00Z",
  },
  {
    id: "usr-005",
    name: "David Brown",
    email: "david.b@example.com",
    role: "Designer",
    department: "Creative",
    permissionGroup: "Regular User",
    status: "inactive",
    lastLogin: "2023-05-28T10:15:00Z",
  },
  {
    id: "usr-006",
    name: "Jessica Lee",
    email: "jessica.l@example.com",
    role: "HR Specialist",
    department: "Human Resources",
    permissionGroup: "HR Admin",
    status: "active",
    lastLogin: "2023-06-14T08:45:00Z",
  },
  {
    id: "usr-007",
    name: "Robert Taylor",
    email: "robert.t@example.com",
    role: "Support Engineer",
    department: "Customer Support",
    permissionGroup: "Technical Staff",
    status: "active",
    lastLogin: "2023-06-15T13:30:00Z",
  },
  {
    id: "usr-008",
    name: "Amanda Wilson",
    email: "amanda.w@example.com",
    role: "Content Writer",
    department: "Marketing",
    permissionGroup: "Regular User",
    status: "inactive",
    lastLogin: "2023-05-20T09:10:00Z",
  },
  {
    id: "usr-009",
    name: "Daniel Martinez",
    email: "daniel.m@example.com",
    role: "Data Scientist",
    department: "Analytics",
    permissionGroup: "Technical Staff",
    status: "active",
    lastLogin: "2023-06-14T17:50:00Z",
  },
  {
    id: "usr-010",
    name: "Olivia Davis",
    email: "olivia.d@example.com",
    role: "Product Manager",
    department: "Product",
    permissionGroup: "Department Head",
    status: "active",
    lastLogin: "2023-06-15T10:05:00Z",
  },
];
